project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path("empresa/", include("empresa.urls"))
]

project/core/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path('', views.home, name="home"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("registrar/", views.registrar, name="registrar"),
    path("about/", views.about, name="about"),
]

urlpatterns += staticfiles_urlpatterns()

project/empresa/urls.py
from django.urls import path
from . import views

app_name = "empresa"

urlpatterns = [
    path('', views.home, name="home"),
    path('empleados/create/', views.empleado_create, name="empleado_create"),
    path('empleados/', views.empleados, name="empleados"),
    path('empleados/buscar/', views.buscar_empleado, name="buscar_empleados"),
    path('empleados/update/<int:pk>', views.empleado_update, name="empleado_update"),
    path('empleados/delete/<int:pk>', views.empleado_delete, name="empleado_delete"),
    path('areas/create/', views.areas_create, name="areas_create"),
    path('areas/detail/<int:pk>', views.areas_detail, name="areas_detail"),
    path('areas/update/<int:pk>', views.areas_update, name="areas_update"),
    path('areas/delete/<int:pk>', views.areas_delete, name="areas_delete"),
]

project/core/models.py
from django.db import models

# Create your models here.

project/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={
            'class': 'form-control',
        })
        self.fields['password'].widget = forms.PasswordInput(attrs={
            'class': 'form-control'
        })

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]
        help_texts = {k: "" for k in fields}

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={'class': 'form-control'})
        self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'form-control'})
        for field_name in self.fields:
            self.fields[field_name].help_text = ''

project/core/views.py
#from django.contrib.admin.views.decorators import staff_member_required
#from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from .forms import CustomAuthenticationForm, CustomUserCreationForm

def home (request):
    return render(request, "core/index.html")

class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "core/login.html"

#@login_required
def registrar(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, "core/index.html", {"mensaje": "Usuario creado"})
    else:
        form = CustomUserCreationForm()
    return render(request, "core/registrar.html", {"form": form})

def about (request):
    return render(request, "core/about.html")

project/core/templates/core/components/footer.html
<!-- Footer-->
<footer class="py-3 bg-dark">
    <div class="container px-5"><p class="m-0 text-center text-white">Mi Proyecto en CoderHouse 2024</p></div>
</footer>

project/core/templates/core/components/head.html
{% load static %}
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta name="description" content="" />
<meta name="author" content="" />
<title>Proyecto CoderHouse</title>
<style>
    footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        padding: 20px;
        
    }
</style>
<!-- Favicon-->
<link rel="icon" type="image/x-icon" href="{% static '/core/assets/favicon.ico'%}"/>
<!-- Bootstrap icons-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
<!-- Core theme CSS (includes Bootstrap)-->
<link href="{% static 'core/css/styles.css'%}"rel="stylesheet" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

project/core/templates/core/components/navbar.html
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">Proyecto CoderHouse</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'empresa:home' %}">Áreas</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'empresa:empleados' %}">Empleados</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'core:about' %}">Sobre Mí</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      {{user.username}}
                    </a>
                    <ul class="dropdown-menu justify-content-center">
                        <li><form action="{% url 'core:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-toolbar  border-0">Cerrar sesión</button>
                            </form>
                        </li>
                    </ul>
                  </li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'core:login' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'core:registrar' %}">Registrarse</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

project/core/templates/core/components/scripts_bootstrap.html
{% load static %}
<!-- Bootstrap core JS-->
<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>-->
<!-- Core theme JS-->
<script src="{% static 'core/js/scripts.js' %}"></script>
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<!-- * *                               SB Forms JS                               * *-->
<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>