project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path("empresa/", include("empresa.urls"))
]

project/core/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path('', views.home, name="home"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("registrar/", views.registrar, name="registrar"),
    path("about/", views.about, name="about"),
]

urlpatterns += staticfiles_urlpatterns()

project/empresa/urls.py
from django.urls import path
from . import views

app_name = "empresa"

urlpatterns = [
    path('', views.home, name="home"),
    path('empleados/create/', views.empleado_create, name="empleado_create"),
    path('empleados/', views.empleados, name="empleados"),
    path('empleados/buscar/', views.buscar_empleado, name="buscar_empleados"),
    path('empleados/update/<int:pk>', views.empleado_update, name="empleado_update"),
    path('empleados/delete/<int:pk>', views.empleado_delete, name="empleado_delete"),
    path('areas/create/', views.areas_create, name="areas_create"),
    path('areas/detail/<int:pk>', views.areas_detail, name="areas_detail"),
    path('areas/update/<int:pk>', views.areas_update, name="areas_update"),
    path('areas/delete/<int:pk>', views.areas_delete, name="areas_delete"),
]

project/empresa/models.py
from django.db import models

class Cargo(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    salario = models.PositiveIntegerField(default=0)
                                              
    def __str__(self):
        return self.nombre

    
class Empleados(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    edad = models.PositiveIntegerField(default=0, null=False)
    documento = models.PositiveIntegerField(default=0, null=False)
    email = models.EmailField(max_length=50, unique=True)
    cargo = models.ForeignKey(Cargo, on_delete=models.SET_NULL, null=True, blank=True)
    avatar = models.ImageField(upload_to="avatares", null=True, blank=True)

    class Meta:
        verbose_name="empleado"
        verbose_name_plural = "empleados"

    def __str__(self) -> str:
        return f"{self.nombre}" + f" {self.apellido}"
     
class Areas(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    descripcion = models.CharField(max_length=1000)
    ubicacion = models.CharField(max_length=100)
    empleados = models.ManyToManyField(Empleados, null=True, blank=True)

    class Meta:
        verbose_name="área"
        verbose_name_plural = "áreas"
    
    def __str__(self) -> str:
        return self.nombre

project/empresa/forms.py
from django import forms

from . import models

class EmpleadosForm(forms.ModelForm):
    class Meta:
        model = models.Empleados
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "apellido": forms.TextInput(attrs={"class": "form-control"}),
            "edad": forms.NumberInput(attrs={"class": "form-control"}),
            "documento": forms.NumberInput(attrs={"class": "form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "cargo": forms.Select(attrs={"class": "form-control"}),
        }

class AreasForm(forms.ModelForm):
    class Meta:
        model = models.Areas
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "descripcion": forms.TextInput(attrs={"class": "form-control"}),
            "ubicacion": forms.TextInput(attrs={"class": "form-control"}),
            "empleados": forms.SelectMultiple(attrs={"class": "form-control"}),
        }

project/empresa/views.py
from django.shortcuts import render, redirect

from . import models, forms

def home (request):
    query = models.Areas.objects.all()
    contexto = {"areas": query}
    return render(request, "empresa/index.html", context=contexto)

def areas_create (request):
    if request.method == "POST":
        form = forms.AreasForm(request.POST)
        try:
            if form.is_valid:
                form.save()
                return redirect("empresa:home")
        except ValueError:
               ...
    else:  # request.method == "GET"
        form = forms.AreasForm()
    return render(request, "empresa/areas_create.html", context={"form": form})


def areas_detail(request, pk: int):
     query = models.Areas.objects.get(id=pk)
     return render(request, "empresa/areas_detail.html", {"area": query})

def areas_update(request, pk: int):
     query = models.Areas.objects.get(id=pk)
     if request.method == "POST":
         form = forms.AreasForm(request.POST, instance=query)
         if form.is_valid:
             form.save()
             return redirect("empresa:home")
     else:  # request.method == "GET"
         form = forms.AreasForm(instance=query)
     return render(request, "empresa/areas_update.html", context={"form": form , "query":query})

def areas_delete(request, pk: int):
    query = models.Areas.objects.get(id=pk)
    if request.method == "POST":
        query.delete()
        return redirect("empresa:home")
    return render(request, "empresa/areas_delete.html", context={"area": query})

def empleados(request):
    query = models.Empleados.objects.all()
    contexto = {"empleados": query}
    return render(request, "empresa/empleados.html", context=contexto)

def empleado_create (request):
    if request.method == "POST":
        form = forms.EmpleadosForm(request.POST)
        try:
            if form.is_valid:
                form.save()
                return redirect("empresa:empleados")
        except ValueError:
               ...
    else:  # request.method == "GET"
        form = forms.EmpleadosForm()
    return render(request, "empresa/empleado_create.html", context={"form": form})

def buscar_empleado(request):
    consulta = request.GET.get("consulta", None)
    if consulta:
        query = models.Empleados.objects.filter(documento__icontains=consulta)
        return render(request, "empresa/buscar_empleado.html", {"resultados": query})
    return render(request, "empresa/buscar_empleado.html")

def empleado_update(request, pk: int):
     query = models.Empleados.objects.get(id=pk)
     if request.method == "POST":
         form = forms.EmpleadosForm(request.POST, instance=query)
         if form.is_valid:
             form.save()
             return redirect("empresa:empleados")
     else:  # request.method == "GET"
         form = forms.EmpleadosForm(instance=query)
     return render(request, "empresa/empleado_update.html", context={"form": form})

def empleado_delete(request, pk: int):
    query = models.Empleados.objects.get(id=pk)
    if request.method == "POST":
        query.delete()
        return redirect("empresa:empleados")
    return render(request, "empresa/empleado_delete.html", context={"empleado": query})

project/empresa/templates/empresa/areas_create.html
{% extends 'core/base.html' %}
{% block title %}
<div class="d-flex bg-opacity-50 bg-secondary align-items-center justify-content-center " ali style="height: 50px; text-align: center;">
    <h3>Crear un area en la base de datos</h3>
  </div>
{% endblock title %}

{% block content %}
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_table }}
        <button type="submit" class="btn btn-primary mt-5">Guardar</button>
        <a href="{% url 'empresa:home' %}" class="btn btn-secondary mt-5">Volver</a>
    </form>
</div>
{% endblock content %}

project/empresa/templates/empresa/areas_delete.html
{% extends 'core/base.html' %}
{% block title %}
<div class="d-flex bg-opacity-50 bg-secondary align-items-center justify-content-center " ali style="height: 50px; text-align: center;">
    <h3>Eliminar area en la base de datos</h3>
  </div>
{% endblock title %}

{% block content %}

<div class="container mt-3 ">
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <div class="card">
            <div class="card-body">
              <h4 class="card-title" style="color:red"><strong>¡Aviso!</strong></h4>
              <p class="card-text">Deseas eliminar <strong>{{area.nombre}}</strong> en la base de datos?</p>
              <button class="btn btn-primary">Eliminar</button>
              <a href="{% url 'empresa:areas_detail' area.id %}" class="btn btn-secondary">Volver</a>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

project/empresa/templates/empresa/areas_detail.html
{% extends 'core/base.html' %}
{% block header_h1 %}
    La empresa
{% endblock header_h1 %}
{% block header_p %}
    Resumen de todas las areas de la empresa
{% endblock header_p %}
{% block title %}
<div class="d-flex bg-opacity-50 bg-secondary align-items-center justify-content-center " ali style="height: 70px; text-align: center;">
    <h1>Detalle del area</h1>
  </div>
{% endblock title %}
{% block content %}

<section class="pt-4 container">
    <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title"><strong>{{area.nombre}} </strong></h5>
          <p class="card-text">{{area.descripcion}}</p>
        </div>
      </div>
</section>

{% if user.is_authenticated %}
<div class="mt-5 container" style="text-align: center;">
    <a href={% url 'empresa:areas_update' area.id %}><button type="button" class="btn btn-primary btn-lg">Editar area</button></a>
    <a href={% url 'empresa:areas_delete' area.id %}><button type="button" class="btn btn-secondary btn-lg">Eliminar area</button></a>
</div>
<div class="container">
    <a href="{% url 'empresa:home'%}" class="btn btn-secondary mt-5" style="margin-bottom: 100px;"> <-- Volver a la vista de areas</a>
</div>
{% endif %}

{% endblock content %}

project/empresa/templates/empresa/areas_update.html
{% extends 'core/base.html' %}
{% block title %}
<div class="d-flex bg-opacity-50 bg-secondary align-items-center justify-content-center " ali style="height: 50px; text-align: center;">
    <h3>Editar un area en la base de datos</h3>
  </div>
{% endblock title %}

{% block content %}
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_table }}
        <button type="submit" class="btn btn-primary mt-5">Guardar</button>
        <a href="{% url 'empresa:areas_detail' query.id %}" class="btn btn-secondary mt-5">Volver</a>
    </form>
</div>
{% endblock content %}

project/empresa/templates/empresa/buscar_empleado.html
{% extends 'core/base.html' %}
{% block title %}
<div class="d-flex bg-opacity-50 bg-secondary align-items-center justify-content-center " ali style="height: 50px; text-align: center;">
    <h3>Buscar un integrante en la base de datos</h3>
  </div>
{% endblock title %}

{% block content %}
<div class="container mt-3">
<form action="{% url 'empresa:buscar_empleados' %}" method="get">
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">DNI:</label>
        <input type="text" class="form-control" name="consulta">
        <div id="emailHelp" class="form-text">Por favor ingresa el DNI del empleado para buscarlo.</div>
      </div>
      <button type="submit" class="btn btn-primary">Buscar</button>
      <a href="{% url 'empresa:empleados' %}" class="btn btn-secondary">Volver</a>
</form>
</div>

{% for resultado in resultados %}
<div class="container align-content-center mt-5">
    <p>El DNI que ingresaste pertenece al empleado:</p>
<div class="card" style="width: 18rem;">
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><strong>{{resultado.nombre}} {{resultado.apellido}}</strong></li>
      <li class="list-group-item"><strong>Cargo: </strong>{{resultado.cargo}}</li>
      <li class="list-group-item"><strong>Correo: </strong>{{resultado.email}}</li>
    </ul>
  </div>
</div>
{% endfor %}

{% endblock content %}

project/empresa/templates/empresa/empleado_create.html
{% extends 'core/base.html' %}
{% block title %}
<div class="d-flex bg-opacity-50 bg-secondary align-items-center justify-content-center " ali style="height: 50px; text-align: center;">
    <h3>Crear un integrante en la base de datos</h3>
  </div>
{% endblock title %}

{% block content %}
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-primary mt-5">Guardar</button>
        <a href="{% url 'empresa:empleados' %}" class="btn btn-secondary mt-5">Volver</a>
    </form>
</div>
{% endblock content %}

project/empresa/templates/empresa/empleado_delete.html
{% extends 'core/base.html' %}
{% block title %}
<div class="d-flex bg-opacity-50 bg-secondary align-items-center justify-content-center " ali style="height: 50px; text-align: center;">
    <h3>Eliminar empleado en la base de datos</h3>
  </div>
{% endblock title %}

{% block content %}

<div class="container mt-3 ">
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <div class="card">
            <div class="card-body">
              <h4 class="card-title" style="color:red"><strong>¡Aviso!</strong></h4>
              <p class="card-text">Deseas eliminar <strong>{{empleado.nombre}} {{empleado.apellido}}</strong> en la base de datos?</p>
              <button class="btn btn-primary">Eliminar</button>
              <a href="{% url 'empresa:empleados' %}" class="btn btn-secondary">Volver</a>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

project/empresa/templates/empresa/empleado_update.html
{% extends 'core/base.html' %}
{% block title %}
<div class="d-flex bg-opacity-50 bg-secondary align-items-center justify-content-center " ali style="height: 50px; text-align: center;">
    <h3>Editar un empleado en la base de datos</h3>
  </div>
{% endblock title %}

{% block content %}
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-primary mt-5">Guardar</button>
        <a href="{% url 'empresa:empleados' %}" class="btn btn-secondary mt-5">Volver</a>
    </form>
</div>
{% endblock content %}

project/empresa/templates/empresa/empleados.html
{% extends 'core/base.html' %}
{% block header_h1 %}
    Nosotros
{% endblock header_h1 %}
{% block header_p %}
    Detalle de las personas que integran nuestro equipo
{% endblock header_p %}
{% block title %}
<div class="d-flex bg-opacity-50 bg-secondary align-items-center justify-content-center " ali style="height: 70px; text-align: center;">
    <h1>Integrantes de nuestro equipo</h1>
  </div>
{% endblock title %}
{% block content %}
{% for empleado in empleados %}
<div class="accordion container mt-3" id="accordionExample-{{ forloop.counter }}">
  <div class="accordion-item">
    <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{ forloop.counter }}" aria-expanded="false" aria-controls="collapse-{{ forloop.counter }}">
        {{empleado.nombre}} {{empleado.apellido}}  
        </button>
    </h2>
    <div id="collapse-{{ forloop.counter }}" class="accordion-collapse collapse" data-bs-parent="#accordionExample-{{ forloop.counter }}">
        <div class="accordion-body">
                <li>
                    Correo: {{empleado.email}}
                </li>
                <li>
                    DNI: {{empleado.documento}}
                </li>
                <li>
                    Cargo: {{empleado.cargo}}
                </li>
                {% if user.is_authenticated %}
                <a href="{% url 'empresa:empleado_update' empleado.id %}"><button type="button" class="btn btn-secondary btn-sm mt-3">Editar</button></a>
                <a href="{% url 'empresa:empleado_delete' empleado.id %}"><button type="button" class="btn btn-danger btn-sm mt-3 ">Eliminar</button></a>
                {% endif %}
        </div>
    </div>
  </div>
</div>
{% endfor %}

{% if user.is_authenticated %}
<div class="mt-5" style="margin-bottom: 50px; text-align: center;">
    <a href={% url 'empresa:empleado_create' %}><button type="button" class="btn btn-secondary btn-lg">Ingresar un nuevo integrante</button>
    </a>
</div>
<div class="mt-2" style="margin-bottom: 100px; text-align: center;">
    <a href={% url 'empresa:buscar_empleados' %}><button type="button" class="btn btn-secondary btn-lg">Buscar un integrante</button>
    </a>
</div>
{% endif %}
<div class="mt-4" style="margin-bottom: 80px; text-align: center;">
    <a href={% url 'core:home' %}><button type="button" class="btn btn-primary btn-lg">Volver al home</button>
    </a>
</div>
{% endblock content%}
    

project/empresa/templates/empresa/index.html
{% extends 'core/base.html' %}
{% block header_h1 %}
    La empresa
{% endblock header_h1 %}
{% block header_p %}
    Resumen de todas las areas de la empresa
{% endblock header_p %}
{% block title %}
<div class="d-flex bg-opacity-50 bg-secondary align-items-center justify-content-center " ali style="height: 70px; text-align: center;">
    <h1>Áreas de la empresa</h1>
  </div>
{% endblock title %}
{% block content %}

<section class="pt-4">
    <div class="container px-lg-5">
        <div class="row gx-lg-5">
            {% for area in areas %}
            <div class="col-lg-6 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="bi bi-collection"> </i></div>
                        <h2 class="fs-4 fw-bold">{{area.nombre}}</h2>
                        <a href="{% url 'empresa:areas_detail' area.id %}">Ver detalle</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% if user.is_authenticated %}
<div class="mt-5" style="margin-bottom: 50px; text-align: center;">
    <a href={% url 'empresa:areas_create' %}><button type="button" class="btn btn-secondary btn-lg">Crear un area nueva</button>
    </a>
</div> 
{% endif %}
<div class="mt-4" style="margin-bottom: 80px; text-align: center;">
    <a href={% url 'core:home' %}><button type="button" class="btn btn-primary btn-lg">Volver al home</button>
    </a>
</div>
{% endblock content %}